apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  namespace: spring-boot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      imagePullSecrets:
        - name: harbor-registry
      containers:
        - name: spring-boot-app
          image: 172.18.0.5:30080/library/spring-boot-app:10
          imagePullPolicy: Always
          ports:
            - containerPort: 8081