FROM jenkins/inbound-agent:latest-jdk17

USER root

RUN apt-get update && apt-get install -y \
    maven \
    git \
    curl \
    sed \
    ca-certificates \
    buildah \
    uidmap \
    libcap2-bin \
 && touch /etc/subuid /etc/subgid \
 && echo 'jenkins:100000:65536' > /etc/subuid \
 && echo 'jenkins:100000:65536' > /etc/subgid \
 && setcap cap_setuid+ep /usr/bin/newuidmap \
 && setcap cap_setgid+ep /usr/bin/newgidmap \
 && chmod u-s /usr/bin/newuidmap /usr/bin/newgidmap \
 && mkdir -p /home/jenkins/.config/containers \
 && mkdir -p /home/jenkins/.local/share/containers/storage \
 && chown -R jenkins:jenkins /home/jenkins/.config /home/jenkins/.local \
 && rm -rf /var/lib/apt/lists/*

ENV HOME=/home/jenkins

USER jenkins