apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-app
  namespace: argocd
spec:
  project: spring-boot-app-project
  source:
    repoURL: https://github.com/mklmfane/argocd-with-jenkins.git
    targetRevision: main
    path: spring-boot-app-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-boot-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true