global:
  domain: argocd.local

configs:
  cm:
    timeout.reconciliation: 120s
    timeout.reconciliation.jitter: 60s

server:
  replicas: 1
  service:
    type: ClusterIP
    servicePortHttp: 80
    servicePortHttps: 443
  ingress:
    enabled: false
  metrics:
    enabled: false

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

controller:
  replicas: 1

redis:
  enabled: true

dex:
  enabled: true

notifications:
  enabled: false
